*HW7* RUTA BASIJOKAITE*;
PROC IMPORT DATAFILE="/folders/myfolders/HW7/Influence.xlsx" /** Import an XLSX file.  **/
		    OUT=WORK.HW7DATA
		    DBMS=XLSX
		    REPLACE;
		    GETNAMES=YES;
		    SCANTEXT=YES;
RUN;
OPTIONS NOCENTER NODATE PAGENO=1 LS=76 PS=45 NOLABEL;
DATA ALL;
  SET HW7DATA;
RUN;
PROC MEANS N MEAN MEDIAN STD MIN MAX MAXDEC=4;
   VAR EXPEND BAD CRIME LAWYERS EMPLOY POP;
   TITLE 'DESCRIPTIVE STATISTICS';
RUN;
PROC CORR PEARSON SPEARMAN;
  VAR EXPEND BAD CRIME LAWYERS EMPLOY POP;
  TITLE 'CORRELATION AMONG VARIABLES';
RUN;
PROC SGSCATTER DATA=ALL;
   MATRIX EXPEND BAD CRIME LAWYERS EMPLOY POP / DIAGONAL=(HISTOGRAM NORMAL);
   TITLE 'EXPEND CORRELATION WITH FIVE PREDICTOR VARIABLES';
RUN;
PROC REG DATA=ALL;
  MODEL EXPEND= BAD CRIME LAWYERS EMPLOY POP / P R INFLUENCE;
  OUTPUT OUT=OUT P=PREDICT R=RESIDUAL STUDENT=STUDENT RSTUDENT=RSTUDENT;
  TITLE 'FULL REGRESSION MODEL';
RUN;
ODS GRAPHICS ON;
PROC SGPLOT DATA=OUT;
  SCATTER X=PREDICT Y=STUDENT;
  REFLINE 0; REFLINE 2; REFLINE -2;
RUN;
PROC SGPLOT DATA=OUT;
  SCATTER X=PREDICT Y=RSTUDENT;
  REFLINE 0; REFLINE 2; REFLINE -2;
RUN;
PROC SGPLOT DATA=OUT;
  SCATTER X=PREDICT Y=RESIDUAL;
  REFLINE 0;
RUN;
ODS GRAPHICS OFF;

