*HW6* RUTA BASIJOKAITE*;
PROC IMPORT DATAFILE="/folders/myfolders/HW6/WLS.xlsx" /** Import an XLSX file.  **/
		    OUT=WORK.HW6DATA
		    DBMS=XLSX
		    REPLACE;
		    GETNAMES=YES;
		    SCANTEXT=YES;
RUN;
OPTIONS NOCENTER NODATE PAGENO=1 LS=76 PS=45 NOLABEL;
DATA ONE;
  SET HW6DATA;
RUN;
PROC REG DATA=ONE;
  MODEL Y=X1 X2 / SPEC ACOV; 
  OUTPUT OUT=OUT1 P=PREDICT R=RESIDUAL; 
RUN;
ODS GRAPHICS ON;
*PROC SGPLOT DATA=OUT1;
*  SCATTER X=PREDICT Y=RESIDUAL;
*  REFLINE 0;
*RUN;
DATA TWO;
  SET OUT1;
  IF X2<40 THEN G=1;
  ELSE IF X2>=40 AND X2<60 THEN G=2;
  ELSE IF X2 >=60 THEN G=3;
RUN;
PROC SORT DATA=TWO;
  BY G;
RUN;
PROC MEANS N MEAN VAR NOPRINT DATA=TWO;
  VAR RESIDUAL;
  BY G;
  OUTPUT OUT=OUT2 N=N MEAN=MEAN VAR=VAR;
RUN;
PROC PRINT DATA=OUT2;
  VAR G N MEAN VAR;
RUN;
* WEIGHTED LEAST SQUARES REGRESSION;
DATA ALL;
  MERGE TWO OUT2;
  BY G;
  W=1/VAR;
RUN;
PROC REG DATA=ALL;
  MODEL Y=X1 X2 / SPEC; 
  WEIGHT W;
  OUTPUT OUT=OUT3 P=PREDICT R=RESIDUAL; 
RUN;
DATA OUT4;
  SET OUT3;
  WLS_RESIDUAL=SQRT(W)*RESIDUAL;
RUN;
PROC SGPLOT DATA=OUT4;
  SCATTER X=PREDICT Y=RESIDUAL;
  REFLINE 0;
RUN;
PROC SGPLOT DATA=OUT4;
  SCATTER X=PREDICT Y=WLS_RESIDUAL;
  REFLINE 0;
RUN;
ODS GRAPHICS OFF;

  






