*HW3* RUTA BASIJOKAITE*;
PROC IMPORT DATAFILE="/folders/myfolders/HW3/MLP.xlsx" /** Import an XLSX file.  **/
		    OUT=WORK.HW3DATA
		    DBMS=XLSX
		    REPLACE;
		    GETNAMES=YES;
RUN;
OPTIONS NOCENTER NODATE PAGENO=1 LS=76 PS=45 NOLABEL;
DATA ALL;
  SET HW3DATA;
RUN;
*TITLE 'DESCRIPTIVE STATISTICS';
PROC MEANS N MEAN MEDIAN STD MIN MAX MAXDEC=4;
   VAR WT SIZE HP BARR MPG;
   TITLE 'DESCRIPTIVE STATISTICS';
 RUN;
 PROC CORR PEARSON SPEARMAN;
   VAR WT SIZE HP BARR MPG;
   TITLE 'CORRELATION BETWEEN VARIABLES';
 RUN;
 PROC SGSCATTER DATA=ALL;
   MATRIX MPG WT SIZE HP BARR / DIAGONAL=(HISTOGRAM NORMAL);
   TITLE 'MPG CORRELATION WITH FOUR PREDICTOR VARIABLES';
  RUN;
  *FULL REGRESSION MODEL WITH 4 VARIABLES*;
  PROC REG DATA=ALL OUTEST=M1;
    MODEL MPG = WT SIZE HP BARR / STB RSQUARE ADJRSQ RMSE PRESS AIC BIC;
  PROC PRINT DATA=M1;
  TITLE 'FULL REGRESSION MODEL WITH 4 VARIABLES';
  RUN;
  *STEPWISE SELECTION*;
  PROC REG DATA=ALL;
    MODEL MPG = WT SIZE HP BARR / SELECTION=STEPWISE SLE=0.15 SLS=0.05;
  TITLE'STEPWISE SELECTION OF VARAIBLES';
  RUN;
  PROC REG DATA=ALL OUTEST=M2;
    MODEL MPG = WT HP / STB RSQUARE ADJRSQ RMSE PRESS AIC BIC;
  PROC PRINT DATA=M2;
  TITLE 'BEST REGRESSION MODEL WITH 2 VARIABLES DETERMINED USING STEPWISE';
  RUN;
  